### ISSUE TITLE
How about predicting an absolute offset?

### ISSUE THREAD

**Issue by Jiayi719** [sel118/LaneAF#23]
Hi, I have tried affinity field in my model. The performance is basically in my expectation. And I have done a contrast experiment between predicting an actual vector (an absolute offset) and an unit vector. The former's performance is quite worse than the latter. The  thresholds are both tuned to a good state respectively.  I think the module of the vector should have some help in clustering. But it seems that predicting an absolute offset is harder to learn. Do you have any idea about this?

**Comment by arangesh** [comment]
This is somewhat expected because with unit vectors, you have one less degree of freedom (the magnitude). When predicting the actual vector, you are trying to predict the magnitude in addition to the direction -  which may require more data/augmentation/training tricks. 
Moreover, unlike unit vector coordinates, the actual vector is not bounded to a range (for example, `[0, 1]`), and this is another challenge that you would have to address.
