### ISSUE TITLE
OpenCV resize will block while using multi-process.

### ISSUE THREAD

**Issue by qinjian623** [sel118/LaneAF#7]
I've located the problem.

https://github.com/sel118/LaneAF/blob/6f020686166660d63e4abf939901394c75bf12db/datasets/culane.py#L127

Resize here will block the whole program.

How to avoid this?

**Comment by arangesh** [comment]
Resizing to this size is essential because of the input requirements of DLA-34. I have not encountered any blocking behavior at my end. Were you able to produce this issue?
If you have to, I would suggest replacing the `cv2.resize()` function with PILs `Image.resize()` or something similar. You may have to convert the arrays to PIL images and back to do this though.

**Comment by bqhuyy** [comment]
Opencv version installed from conda cause this problem. Pip version of opencv can solve this problem: `pip install opencv-python`

**Comment by qinjian623** [comment]
> Opencv version installed from **conda** causes this problem. **Pip** version of opencv can solve this problem: `pip install opencv-python`

It works now. Thank you.

**Comment by arangesh** [comment]
I have updated README to reflect this. Closing the issue now.
